language: python

env:
    - CONDA="python=2.7"
    #- CONDA="python=3.4"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - travis_retry conda create --yes -n test $CONDA --file requirements.txt
    - source activate test
    - conda info -a
    - conda install --yes --file requirements-dev.txt

install:
    - python setup.py build
    - python setup.py install

script:
    - cd yaml2ncml/tests && py.test
    - find . -type f -name "*.py"|xargs flake8 --max-line-length=100
