language: python

sudo: false

env:
    - CONDA="python=2.7"
    - CONDA="python=3.4"
    - CONDA="python=3.5"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda
    - conda config --add channels conda-forge --force
    - travis_retry conda create --name TEST $CONDA --file requirements.txt --file requirements-dev.txt
    - source activate TEST
    - conda info

install:
    # Test source distribution.
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install yaml2ncml-${version}.tar.gz && popd

script:
    # Test must be run inside the `test` directory because the yaml2ncml expect the data path to be relative.
    - find . -type f -name "*.py" | xargs flake8 --max-line-length=100
    - cd tests && py.test
